trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# Build using Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# Copy JAR to artifact staging
- task: CopyFiles@2
  inputs:
    contents: '**/target/*.jar'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

# Publish build artifacts for release pipeline
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
